name: app_developments
# description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flavor: ^2.0.0

  # Localization
  intl: ^0.18.0
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.5

dev_dependencies:
  dart_code_metrics: ^5.7.3
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true